theme: minima
title: {CLAUSTRUM}
author: marcelo bascur
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Pensando como hacer una pagina 
  para neuropediatras hispanos

# social links
twitter_username: caezonbascur # DO NOT include the @ character, or else the build will fail!
github_username:  MBascur # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
